CREATE TABLE ORGANIZATION(
	ID UUID PRIMARY KEY,
	NAME VARCHAR(25),
	
	CONSTRAINT NN_NAME CHECK (NAME IS NOT NULL)
);

CREATE TABLE SERVICE_USER(
	ID UUID PRIMARY KEY,
	FIRST_NAME VARCHAR(25) NOT NULL,
	LAST_NAME VARCHAR(25) NOT NULL,
	PASSWORD VARCHAR(60) NOT NULL,
	EMAIL VARCHAR(25) NOT NULL,
	FK_ORG UUID,
	
	CONSTRAINT FK_ORG FOREIGN KEY (FK_ORG) REFERENCES ORGANIZATION(ID) ON DELETE CASCADE,
	CONSTRAINT NN_FIRST_NAME CHECK (FIRST_NAME IS NOT NULL),
	CONSTRAINT NN_LAST_NAME CHECK (LAST_NAME IS NOT NULL),
	CONSTRAINT NN_PASSWORD CHECK (PASSWORD IS NOT NULL),
	CONSTRAINT NN_EMAIL CHECK (EMAIL IS NOT NULL)
);

CREATE TABLE DONATION(
	ID UUID PRIMARY KEY,
	TITLE VARCHAR(25),
	DESTINATION VARCHAR(25),
	CREATED_DATE TIMESTAMP,
	FK_AUTHOR UUID,

	CONSTRAINT FK_AUTHOR FOREIGN KEY (FK_AUTHOR) REFERENCES SERVICE_USER(ID) ON DELETE CASCADE,
	CONSTRAINT NN_TITLE CHECK(TITLE IS NOT NULL),
	CONSTRAINT NN_DESTINATION CHECK(DESTINATION IS NOT NULL),
	CONSTRAINT NN_CREATED_DATE CHECK(CREATED_DATE IS NOT NULL)
);

CREATE TABLE MINI_DONATION(
	ID UUID PRIMARY KEY,
	TITLE VARCHAR(25),
	CREATED_DATE TIMESTAMP,
	FK_DONATION UUID,
	FK_AUTHOR UUID,

	CONSTRAINT FK_DONATION FOREIGN KEY (FK_DONATION) REFERENCES DONATION(ID) ON DELETE CASCADE,
	CONSTRAINT FK_AUTHOR FOREIGN KEY (FK_AUTHOR) REFERENCES SERVICE_USER(ID) ON DELETE CASCADE,
	CONSTRAINT UQ_FK_DONATION_AUTHOR UNIQUE (FK_AUTHOR, FK_DONATION)
);  